### ISSUE TITLE
Visualize encoder output

### ISSUE THREAD

**Issue by joshua-shuhan** [media-comp/2022-NRI#4]
Encoder gives edge prediction. A visualization for encoder output results is desirable.

**How to get start**
In the default setting, after running `run_encoder.py`, `_springsLight5output.npy` and `_springsLight5target.npy` will be saved in the `saved_results/encoder_result` folder. `_springsLight5output.npy` gives edge predictions while `_springsLight5target.npy` is the ground truth target.  

**Tips**
The shape of _springsLight5.npy is (200, 100, 2). 200 is the number of batches. There are multiple simulations in one batch (in this case, 5 simulations in one batch). The number of nodes in the simulation is 5. Therefore, for each simulation, the size of edge prediction is (20, 2).

**Comment by joshua-shuhan** [comment]
@[falseu](https://github.com/falseu)
I think node conflict is not a problem for directed graphs. 
For an undirected graph, when conflict, is it ok to take the larger value as the prediction output?
For example, `1->4: [0.6, 0.4]`, `4->1: [0.2, 0.8]`, since 0.8 > 0.6, we choose the second type as the prediction result of the undirected edge.

**Comment by falseu** [comment]
Thank you for your explanation. You mentioned that for each simulation, the number of nodes is 5. If we construct a directed graph without self-loop, then the number of edges is `5*4=20`, which matches the size of edge prediction (20, 2).

We also need the node labels to construct the graph. Then how should we determine the node labels for the 20 edges? Currently I assume the following label assignment. 

```
1->2, 1->3, 1->4, 1->5,
2->1, 2->3, 2->4, 2->5,
3->1, 3->2, 3->4, 3->5,
4->1, 4->2, 4->3, 4->5
5->1, 5->2, 5->3, 5->4
```

Please verify this assignment and I will fix my code accordingly. Thank you.

**Comment by joshua-shuhan** [comment]
Yes, that is the case. 
You can check how the edge is generated [here](https://github.com/media-comp/2022-NRI/blob/e13b0712915c515c168e5cae5e63997a2b90d448/src/synthetic_sim.py#L75).

**Comment by falseu** [comment]
Please review the updated visualization. Thanks.

**Comment by joshua-shuhan** [comment]
LGTM, merged.
